export const ITEM_TYPES = Object.freeze({
  WEAPON: "weapon",
  ARMOR: "armor",
  HELMET: "helmet",
  PANTS: "pants",
  BOOTS: "boots",
  POTION: "potion",
  FOOD: "food",
  MATERIAL: "material",
  GEM: "gem",
  ESSENCE: "essence",
  SCROLL: "scroll",
  BOMB: "bomb",
  TOOL: "tool",
  CONTAINER: "container",
  PICKAXE: "pickaxe",
  SHIELD: "shield",
  RELIC: "relic",
  ELIXIR: "elixir",
});

export const RARITIES = Object.freeze({
  COMMON: "common",
  UNCOMMON: "uncommon",
  RARE: "rare",
  EPIC: "epic",
  LEGENDARY: "legendary",
  MYTHIC: "mythic",
});

const makeItem = ({
  id,
  name,
  type,
  rarity = "common",
  slot = null,
  damage = 0,
  protection = 0,
  durability = 100,
  stackable = false,
  value = 0,
  description = "",
}) => ({
  id,
  name,
  type,
  rarity,
  slot,
  damage,
  protection,
  durability,
  maxDurability: durability,
  stackable,
  value,
  description,
});

export const ITEMS = Object.freeze({
  // =========================
  // ARMADURAS DE CUERO
  // =========================
  leather_helmet: makeItem({
    id: "leather_helmet",
    name: "Leather Helmet",
    type: "armor",
    rarity: "common",
    slot: "head",
    protection: 2,
    durability: 100,
    value: 15,
    description: "Casco de cuero básico.",
  }),
  leather_chestplate: makeItem({
    id: "leather_chestplate",
    name: "Leather Chestplate",
    type: "armor",
    rarity: "common",
    slot: "body",
    protection: 4,
    durability: 100,
    value: 25,
    description: "Pecho de cuero básico.",
  }),
  leather_leggings: makeItem({
    id: "leather_leggings",
    name: "Leather Leggings",
    type: "armor",
    rarity: "common",
    slot: "legs",
    protection: 3,
    durability: 100,
    value: 20,
    description: "Pantalones de cuero básicos.",
  }),
  leather_boots: makeItem({
    id: "leather_boots",
    name: "Leather Boots",
    type: "armor",
    rarity: "common",
    slot: "feet",
    protection: 1,
    durability: 100,
    value: 10,
    description: "Botas de cuero básicas.",
  }),

  // =========================
  // ARMADURAS DE CADENA
  // =========================
  chainmail_helmet: makeItem({
    id: "chainmail_helmet",
    name: "Chainmail Helmet",
    type: "armor",
    rarity: "uncommon",
    slot: "head",
    protection: 3,
    durability: 100,
    value: 35,
    description: "Casco de cota de malla.",
  }),
  chainmail_chestplate: makeItem({
    id: "chainmail_chestplate",
    name: "Chainmail Chestplate",
    type: "armor",
    rarity: "uncommon",
    slot: "body",
    protection: 5,
    durability: 100,
    value: 55,
    description: "Pecho de cota de malla.",
  }),
  chainmail_leggings: makeItem({
    id: "chainmail_leggings",
    name: "Chainmail Leggings",
    type: "armor",
    rarity: "uncommon",
    slot: "legs",
    protection: 4,
    durability: 100,
    value: 45,
    description: "Pantalones de cota de malla.",
  }),
  chainmail_boots: makeItem({
    id: "chainmail_boots",
    name: "Chainmail Boots",
    type: "armor",
    rarity: "uncommon",
    slot: "feet",
    protection: 2,
    durability: 100,
    value: 25,
    description: "Botas de cota de malla.",
  }),

  // =========================
  // ARMADURAS DE HIERRO
  // =========================
  iron_helmet: makeItem({
    id: "iron_helmet",
    name: "Iron Helmet",
    type: "armor",
    rarity: "rare",
    slot: "head",
    protection: 4,
    durability: 100,
    value: 70,
    description: "Casco de hierro.",
  }),
  iron_chestplate: makeItem({
    id: "iron_chestplate",
    name: "Iron Chestplate",
    type: "armor",
    rarity: "rare",
    slot: "body",
    protection: 7,
    durability: 100,
    value: 110,
    description: "Pecho de hierro.",
  }),
  iron_leggings: makeItem({
    id: "iron_leggings",
    name: "Iron Leggings",
    type: "armor",
    rarity: "rare",
    slot: "legs",
    protection: 6,
    durability: 100,
    value: 90,
    description: "Pantalones de hierro.",
  }),
  iron_boots: makeItem({
    id: "iron_boots",
    name: "Iron Boots",
    type: "armor",
    rarity: "rare",
    slot: "feet",
    protection: 3,
    durability: 100,
    value: 60,
    description: "Botas de hierro.",
  }),

  // =========================
  // ARMADURAS DE ORO
  // =========================
  gold_helmet: makeItem({
    id: "gold_helmet",
    name: "Gold Helmet",
    type: "armor",
    rarity: "rare",
    slot: "head",
    protection: 4,
    durability: 100,
    value: 85,
    description: "Casco de oro.",
  }),
  gold_chestplate: makeItem({
    id: "gold_chestplate",
    name: "Gold Chestplate",
    type: "armor",
    rarity: "rare",
    slot: "body",
    protection: 6,
    durability: 100,
    value: 130,
    description: "Pecho de oro.",
  }),
  gold_leggings: makeItem({
    id: "gold_leggings",
    name: "Gold Leggings",
    type: "armor",
    rarity: "rare",
    slot: "legs",
    protection: 5,
    durability: 100,
    value: 105,
    description: "Pantalones de oro.",
  }),
  gold_boots: makeItem({
    id: "gold_boots",
    name: "Gold Boots",
    type: "armor",
    rarity: "rare",
    slot: "feet",
    protection: 2,
    durability: 100,
    value: 70,
    description: "Botas de oro.",
  }),

  // =========================
  // ARMADURAS DE DIAMANTE
  // =========================
  diamond_helmet: makeItem({
    id: "diamond_helmet",
    name: "Diamond Helmet",
    type: "armor",
    rarity: "epic",
    slot: "head",
    protection: 6,
    durability: 100,
    value: 180,
    description: "Casco de diamante.",
  }),
  diamond_chestplate: makeItem({
    id: "diamond_chestplate",
    name: "Diamond Chestplate",
    type: "armor",
    rarity: "epic",
    slot: "body",
    protection: 10,
    durability: 100,
    value: 280,
    description: "Pecho de diamante.",
  }),
  diamond_leggings: makeItem({
    id: "diamond_leggings",
    name: "Diamond Leggings",
    type: "armor",
    rarity: "epic",
    slot: "legs",
    protection: 8,
    durability: 100,
    value: 240,
    description: "Pantalones de diamante.",
  }),
  diamond_boots: makeItem({
    id: "diamond_boots",
    name: "Diamond Boots",
    type: "armor",
    rarity: "epic",
    slot: "feet",
    protection: 5,
    durability: 100,
    value: 160,
    description: "Botas de diamante.",
  }),

  // =========================
  // ARMADURAS DE NETHERITE
  // =========================
  netherite_helmet: makeItem({
    id: "netherite_helmet",
    name: "Netherite Helmet",
    type: "armor",
    rarity: "legendary",
    slot: "head",
    protection: 8,
    durability: 100,
    value: 360,
    description: "Casco de netherite.",
  }),
  netherite_chestplate: makeItem({
    id: "netherite_chestplate",
    name: "Netherite Chestplate",
    type: "armor",
    rarity: "legendary",
    slot: "body",
    protection: 13,
    durability: 100,
    value: 520,
    description: "Pecho de netherite.",
  }),
  netherite_leggings: makeItem({
    id: "netherite_leggings",
    name: "Netherite Leggings",
    type: "armor",
    rarity: "legendary",
    slot: "legs",
    protection: 11,
    durability: 100,
    value: 460,
    description: "Pantalones de netherite.",
  }),
  netherite_boots: makeItem({
    id: "netherite_boots",
    name: "Netherite Boots",
    type: "armor",
    rarity: "legendary",
    slot: "feet",
    protection: 7,
    durability: 100,
    value: 320,
    description: "Botas de netherite.",
  }),

  // =========================
  // ARMADURAS MÍTICAS
  // =========================
  dragon_helmet: makeItem({
    id: "dragon_helmet",
    name: "Dragon Helmet",
    type: "armor",
    rarity: "mythic",
    slot: "head",
    protection: 10,
    durability: 100,
    value: 800,
    description: "Casco del dragón.",
  }),
  dragon_chestplate: makeItem({
    id: "dragon_chestplate",
    name: "Dragon Chestplate",
    type: "armor",
    rarity: "mythic",
    slot: "body",
    protection: 16,
    durability: 100,
    value: 1200,
    description: "Pecho del dragón.",
  }),
  dragon_leggings: makeItem({
    id: "dragon_leggings",
    name: "Dragon Leggings",
    type: "armor",
    rarity: "mythic",
    slot: "legs",
    protection: 14,
    durability: 100,
    value: 1100,
    description: "Pantalones del dragón.",
  }),
  dragon_boots: makeItem({
    id: "dragon_boots",
    name: "Dragon Boots",
    type: "armor",
    rarity: "mythic",
    slot: "feet",
    protection: 9,
    durability: 100,
    value: 750,
    description: "Botas del dragón.",
  }),

  // =========================
  // CASCOS ESPECIALES
  // =========================
  crown_of_ash: makeItem({
    id: "crown_of_ash",
    name: "Crown of Ash",
    type: "helmet",
    rarity: "mythic",
    slot: "head",
    protection: 18,
    durability: 100,
    value: 3000,
    description: "Corona ardiente de alto nivel.",
  }),
  void_helm: makeItem({
    id: "void_helm",
    name: "Void Helm",
    type: "helmet",
    rarity: "legendary",
    slot: "head",
    protection: 12,
    durability: 100,
    value: 1800,
    description: "Casco del vacío.",
  }),
  royal_helm: makeItem({
    id: "royal_helm",
    name: "Royal Helm",
    type: "helmet",
    rarity: "epic",
    slot: "head",
    protection: 9,
    durability: 100,
    value: 900,
    description: "Casco real.",
  }),

  // =========================
  // PANTALONES ESPECIALES
  // =========================
  shadow_leggings: makeItem({
    id: "shadow_leggings",
    name: "Shadow Leggings",
    type: "pants",
    rarity: "legendary",
    slot: "legs",
    protection: 12,
    durability: 100,
    value: 1700,
    description: "Pantalones sombríos.",
  }),
  warrior_pants: makeItem({
    id: "warrior_pants",
    name: "Warrior Pants",
    type: "pants",
    rarity: "epic",
    slot: "legs",
    protection: 9,
    durability: 100,
    value: 850,
    description: "Pantalones de guerrero.",
  }),
  titan_pants: makeItem({
    id: "titan_pants",
    name: "Titan Pants",
    type: "pants",
    rarity: "mythic",
    slot: "legs",
    protection: 15,
    durability: 100,
    value: 2200,
    description: "Pantalones titánicos.",
  }),

  // =========================
  // BOTAS ESPECIALES
  // =========================
  boots_of_wind: makeItem({
    id: "boots_of_wind",
    name: "Boots of Wind",
    type: "boots",
    rarity: "epic",
    slot: "feet",
    protection: 8,
    durability: 100,
    value: 900,
    description: "Botas veloces del viento.",
  }),
  abyss_boots: makeItem({
    id: "abyss_boots",
    name: "Abyss Boots",
    type: "boots",
    rarity: "legendary",
    slot: "feet",
    protection: 10,
    durability: 100,
    value: 1400,
    description: "Botas del abismo.",
  }),
  celestial_boots: makeItem({
    id: "celestial_boots",
    name: "Celestial Boots",
    type: "boots",
    rarity: "mythic",
    slot: "feet",
    protection: 13,
    durability: 100,
    value: 2600,
    description: "Botas celestiales.",
  }),

  // =========================
  // ESPADAS
  // =========================
  wooden_sword: makeItem({
    id: "wooden_sword",
    name: "Wooden Sword",
    type: "weapon",
    rarity: "common",
    slot: "hand",
    damage: 4,
    durability: 100,
    value: 20,
    description: "Espada de madera.",
  }),
  stone_sword: makeItem({
    id: "stone_sword",
    name: "Stone Sword",
    type: "weapon",
    rarity: "common",
    slot: "hand",
    damage: 5,
    durability: 100,
    value: 30,
    description: "Espada de piedra.",
  }),
  iron_sword: makeItem({
    id: "iron_sword",
    name: "Iron Sword",
    type: "weapon",
    rarity: "rare",
    slot: "hand",
    damage: 6,
    durability: 100,
    value: 90,
    description: "Espada de hierro.",
  }),
  golden_sword: makeItem({
    id: "golden_sword",
    name: "Golden Sword",
    type: "weapon",
    rarity: "rare",
    slot: "hand",
    damage: 5,
    durability: 100,
    value: 100,
    description: "Espada de oro.",
  }),
  diamond_sword: makeItem({
    id: "diamond_sword",
    name: "Diamond Sword",
    type: "weapon",
    rarity: "epic",
    slot: "hand",
    damage: 8,
    durability: 100,
    value: 220,
    description: "Espada de diamante.",
  }),
  netherite_sword: makeItem({
    id: "netherite_sword",
    name: "Netherite Sword",
    type: "weapon",
    rarity: "legendary",
    slot: "hand",
    damage: 10,
    durability: 100,
    value: 380,
    description: "Espada de netherite.",
  }),
  dragon_sword: makeItem({
    id: "dragon_sword",
    name: "Dragon Sword",
    type: "weapon",
    rarity: "mythic",
    slot: "hand",
    damage: 14,
    durability: 100,
    value: 900,
    description: "Espada del dragón.",
  }),
  sun_blade: makeItem({
    id: "sun_blade",
    name: "Sun Blade",
    type: "weapon",
    rarity: "mythic",
    slot: "hand",
    damage: 15,
    durability: 100,
    value: 1200,
    description: "Hoja solar.",
  }),
  moon_blade: makeItem({
    id: "moon_blade",
    name: "Moon Blade",
    type: "weapon",
    rarity: "mythic",
    slot: "hand",
    damage: 15,
    durability: 100,
    value: 1200,
    description: "Hoja lunar.",
  }),

  // =========================
  // HACHAS
  // =========================
  wooden_axe: makeItem({
    id: "wooden_axe",
    name: "Wooden Axe",
    type: "weapon",
    rarity: "common",
    slot: "hand",
    damage: 5,
    durability: 100,
    value: 18,
    description: "Hacha de madera.",
  }),
  stone_axe: makeItem({
    id: "stone_axe",
    name: "Stone Axe",
    type: "weapon",
    rarity: "common",
    slot: "hand",
    damage: 6,
    durability: 100,
    value: 28,
    description: "Hacha de piedra.",
  }),
  iron_axe: makeItem({
    id: "iron_axe",
    name: "Iron Axe",
    type: "weapon",
    rarity: "rare",
    slot: "hand",
    damage: 7,
    durability: 100,
    value: 85,
    description: "Hacha de hierro.",
  }),
  golden_axe: makeItem({
    id: "golden_axe",
    name: "Golden Axe",
    type: "weapon",
    rarity: "rare",
    slot: "hand",
    damage: 5,
    durability: 100,
    value: 95,
    description: "Hacha de oro.",
  }),
  diamond_axe: makeItem({
    id: "diamond_axe",
    name: "Diamond Axe",
    type: "weapon",
    rarity: "epic",
    slot: "hand",
    damage: 9,
    durability: 100,
    value: 210,
    description: "Hacha de diamante.",
  }),
  netherite_axe: makeItem({
    id: "netherite_axe",
    name: "Netherite Axe",
    type: "weapon",
    rarity: "legendary",
    slot: "hand",
    damage: 11,
    durability: 100,
    value: 360,
    description: "Hacha de netherite.",
  }),

  // =========================
  // DAGAS Y ARMAS RÁPIDAS
  // =========================
  rusty_dagger: makeItem({
    id: "rusty_dagger",
    name: "Rusty Dagger",
    type: "weapon",
    rarity: "common",
    slot: "hand",
    damage: 3,
    durability: 100,
    value: 10,
    description: "Daga oxidada.",
  }),
  steel_dagger: makeItem({
    id: "steel_dagger",
    name: "Steel Dagger",
    type: "weapon",
    rarity: "rare",
    slot: "hand",
    damage: 5,
    durability: 100,
    value: 70,
    description: "Daga de acero.",
  }),
  assassin_dagger: makeItem({
    id: "assassin_dagger",
    name: "Assassin Dagger",
    type: "weapon",
    rarity: "epic",
    slot: "hand",
    damage: 8,
    durability: 100,
    value: 180,
    description: "Daga de asesino.",
  }),

  // =========================
  // LANCAS
  // =========================
  wooden_spear: makeItem({
    id: "wooden_spear",
    name: "Wooden Spear",
    type: "weapon",
    rarity: "common",
    slot: "hand",
    damage: 4,
    durability: 100,
    value: 14,
    description: "Lanza de madera.",
  }),
  iron_spear: makeItem({
    id: "iron_spear",
    name: "Iron Spear",
    type: "weapon",
    rarity: "rare",
    slot: "hand",
    damage: 7,
    durability: 100,
    value: 80,
    description: "Lanza de hierro.",
  }),
  diamond_spear: makeItem({
    id: "diamond_spear",
    name: "Diamond Spear",
    type: "weapon",
    rarity: "epic",
    slot: "hand",
    damage: 9,
    durability: 100,
    value: 200,
    description: "Lanza de diamante.",
  }),
  dragon_spear: makeItem({
    id: "dragon_spear",
    name: "Dragon Spear",
    type: "weapon",
    rarity: "mythic",
    slot: "hand",
    damage: 12,
    durability: 100,
    value: 700,
    description: "Lanza del dragón.",
  }),

  // =========================
  // BOWS Y ARTEFACTOS
  // =========================
  hunter_bow: makeItem({
    id: "hunter_bow",
    name: "Hunter Bow",
    type: "weapon",
    rarity: "uncommon",
    slot: "hand",
    damage: 5,
    durability: 100,
    value: 45,
    description: "Arco de cazador.",
  }),
  war_bow: makeItem({
    id: "war_bow",
    name: "War Bow",
    type: "weapon",
    rarity: "rare",
    slot: "hand",
    damage: 7,
    durability: 100,
    value: 90,
    description: "Arco de guerra.",
  }),
  elven_bow: makeItem({
    id: "elven_bow",
    name: "Elven Bow",
    type: "weapon",
    rarity: "epic",
    slot: "hand",
    damage: 10,
    durability: 100,
    value: 200,
    description: "Arco élfico.",
  }),
  shadow_crossbow: makeItem({
    id: "shadow_crossbow",
    name: "Shadow Crossbow",
    type: "weapon",
    rarity: "legendary",
    slot: "hand",
    damage: 11,
    durability: 100,
    value: 260,
    description: "Ballesta sombría.",
  }),
  mage_staff: makeItem({
    id: "mage_staff",
    name: "Mage Staff",
    type: "weapon",
    rarity: "rare",
    slot: "hand",
    damage: 8,
    durability: 100,
    value: 85,
    description: "Bastón de mago.",
  }),
  arcane_staff: makeItem({
    id: "arcane_staff",
    name: "Arcane Staff",
    type: "weapon",
    rarity: "epic",
    slot: "hand",
    damage: 12,
    durability: 100,
    value: 220,
    description: "Bastón arcano.",
  }),
  storm_hammer: makeItem({
    id: "storm_hammer",
    name: "Storm Hammer",
    type: "weapon",
    rarity: "mythic",
    slot: "hand",
    damage: 14,
    durability: 100,
    value: 550,
    description: "Martillo de tormenta.",
  }),

  // =========================
  // ESCUDOS
  // =========================
  guardian_shield: makeItem({
    id: "guardian_shield",
    name: "Guardian Shield",
    type: "shield",
    rarity: "epic",
    slot: "offhand",
    damage: 0,
    protection: 12,
    durability: 100,
    value: 250,
    description: "Escudo guardián.",
  }),
  tower_shield: makeItem({
    id: "tower_shield",
    name: "Tower Shield",
    type: "shield",
    rarity: "legendary",
    slot: "offhand",
    damage: 0,
    protection: 15,
    durability: 100,
    value: 420,
    description: "Escudo torre.",
  }),

// =========================
  // POCIONES
  // =========================
  potion_healing: makeItem({
    id: "potion_healing",
    name: "Healing Potion",
    type: "potion",
    rarity: "common",
    stackable: true,
    durability: 1,
    value: 20,
    description: "Poción de curación.",
  }),
  potion_large_healing: makeItem({
    id: "potion_large_healing",
    name: "Large Healing Potion",
    type: "potion",
    rarity: "rare",
    stackable: true,
    durability: 1,
    value: 60,
    description: "Poción grande de curación.",
  }),
  potion_mana: makeItem({
    id: "potion_mana",
    name: "Mana Potion",
    type: "potion",
    rarity: "common",
    stackable: true,
    durability: 1,
    value: 18,
    description: "Poción de maná.",
  }),
  potion_strength: makeItem({
    id: "potion_strength",
    name: "Strength Potion",
    type: "potion",
    rarity: "rare",
    stackable: true,
    durability: 1,
    value: 45,
    description: "Poción de fuerza.",
  }),
  potion_speed: makeItem({
    id: "potion_speed",
    name: "Speed Potion",
    type: "potion",
    rarity: "uncommon",
    stackable: true,
    durability: 1,
    value: 30,
    description: "Poción de velocidad.",
  }),
  potion_regeneration: makeItem({
    id: "potion_regeneration",
    name: "Regeneration Potion",
    type: "potion",
    rarity: "epic",
    stackable: true,
    durability: 1,
    value: 90,
    description: "Poción de regeneración.",
  }),
  potion_poison: makeItem({
    id: "potion_poison",
    name: "Poison Potion",
    type: "potion",
    rarity: "uncommon",
    stackable: true,
    durability: 1,
    value: 25,
    description: "Poción venenosa.",
  }),
  potion_fire_resistance: makeItem({
    id: "potion_fire_resistance",
    name: "Fire Resistance Potion",
    type: "potion",
    rarity: "rare",
    stackable: true,
    durability: 1,
    value: 35,
    description: "Resistencia al fuego.",
  }),
  potion_water_breathing: makeItem({
    id: "potion_water_breathing",
    name: "Water Breathing Potion",
    type: "potion",
    rarity: "rare",
    stackable: true,
    durability: 1,
    value: 35,
    description: "Respiración acuática.",
  }),
  potion_invisibility: makeItem({
    id: "potion_invisibility",
    name: "Invisibility Potion",
    type: "potion",
    rarity: "legendary",
    stackable: true,
    durability: 1,
    value: 120,
    description: "Poción de invisibilidad.",
  }),

  // =========================
  // COMIDA
  // =========================
  food_apple: makeItem({
    id: "food_apple",
    name: "Apple",
    type: "food",
    rarity: "common",
    stackable: true,
    durability: 1,
    value: 10,
    description: "Manzana.",
  }),
  food_bread: makeItem({
    id: "food_bread",
    name: "Bread",
    type: "food",
    rarity: "common",
    stackable: true,
    durability: 1,
    value: 12,
    description: "Pan.",
  }),
  food_meat: makeItem({
    id: "food_meat",
    name: "Cooked Meat",
    type: "food",
    rarity: "common",
    stackable: true,
    durability: 1,
    value: 20,
    description: "Carne cocinada.",
  }),
  food_gold_apple: makeItem({
    id: "food_gold_apple",
    name: "Golden Apple",
    type: "food",
    rarity: "epic",
    stackable: true,
    durability: 1,
    value: 80,
    description: "Manzana dorada.",
  }),

  // =========================
  // MATERIALES
  // =========================
  ore_iron: makeItem({
    id: "ore_iron",
    name: "Iron Ore",
    type: "material",
    rarity: "common",
    stackable: true,
    durability: 1,
    value: 15,
    description: "Mineral de hierro.",
  }),
  ore_gold: makeItem({
    id: "ore_gold",
    name: "Gold Ore",
    type: "material",
    rarity: "uncommon",
    stackable: true,
    durability: 1,
    value: 35,
    description: "Mineral de oro.",
  }),
  ore_diamond: makeItem({
    id: "ore_diamond",
    name: "Diamond Ore",
    type: "material",
    rarity: "rare",
    stackable: true,
    durability: 1,
    value: 120,
    description: "Mineral de diamante.",
  }),
  ore_mythril: makeItem({
    id: "ore_mythril",
    name: "Mythril Ore",
    type: "material",
    rarity: "epic",
    stackable: true,
    durability: 1,
    value: 300,
    description: "Mineral de mythril.",
  }),
  steel_ingot: makeItem({
    id: "steel_ingot",
    name: "Steel Ingot",
    type: "material",
    rarity: "rare",
    stackable: true,
    durability: 1,
    value: 80,
    description: "Lingote de acero.",
  }),
  mithril_ingot: makeItem({
    id: "mithril_ingot",
    name: "Mythril Ingot",
    type: "material",
    rarity: "epic",
    stackable: true,
    durability: 1,
    value: 220,
    description: "Lingote de mythril.",
  }),
  cloth_fine: makeItem({
    id: "cloth_fine",
    name: "Fine Cloth",
    type: "material",
    rarity: "common",
    stackable: true,
    durability: 1,
    value: 25,
    description: "Tela fina.",
  }),
  leather_strip: makeItem({
    id: "leather_strip",
    name: "Leather Strip",
    type: "material",
    rarity: "common",
    stackable: true,
    durability: 1,
    value: 20,
    description: "Tira de cuero.",
  }),
  dragon_scale: makeItem({
    id: "dragon_scale",
    name: "Dragon Scale",
    type: "material",
    rarity: "mythic",
    stackable: true,
    durability: 1,
    value: 2000,
    description: "Escama de dragón.",
  }),
  ancient_relic: makeItem({
    id: "ancient_relic",
    name: "Ancient Relic",
    type: "relic",
    rarity: "legendary",
    stackable: true,
    durability: 1,
    value: 1000,
    description: "Reliquia antigua.",
  }),

  // =========================
  // GEMAS Y ESENCIAS
  // =========================
  gem_ruby: makeItem({
    id: "gem_ruby",
    name: "Ruby",
    type: "gem",
    rarity: "rare",
    stackable: true,
    durability: 1,
    value: 180,
    description: "Rubí.",
  }),
  gem_sapphire: makeItem({
    id: "gem_sapphire",
    name: "Sapphire",
    type: "gem",
    rarity: "rare",
    stackable: true,
    durability: 1,
    value: 180,
    description: "Zafiro.",
  }),
  gem_emerald: makeItem({
    id: "gem_emerald",
    name: "Emerald",
    type: "gem",
    rarity: "epic",
    stackable: true,
    durability: 1,
    value: 260,
    description: "Esmeralda.",
  }),
  gem_amethyst: makeItem({
    id: "gem_amethyst",
    name: "Amethyst",
    type: "gem",
    rarity: "epic",
    stackable: true,
    durability: 1,
    value: 260,
    description: "Amatista.",
  }),
  essence_fire: makeItem({
    id: "essence_fire",
    name: "Fire Essence",
    type: "essence",
    rarity: "uncommon",
    stackable: true,
    durability: 1,
    value: 90,
    description: "Esencia de fuego.",
  }),
  essence_ice: makeItem({
    id: "essence_ice",
    name: "Ice Essence",
    type: "essence",
    rarity: "uncommon",
    stackable: true,
    durability: 1,
    value: 90,
    description: "Esencia de hielo.",
  }),
  essence_light: makeItem({
    id: "essence_light",
    name: "Light Essence",
    type: "essence",
    rarity: "legendary",
    stackable: true,
    durability: 1,
    value: 450,
    description: "Esencia de luz.",
  }),
  essence_dark: makeItem({
    id: "essence_dark",
    name: "Dark Essence",
    type: "essence",
    rarity: "legendary",
    stackable: true,
    durability: 1,
    value: 450,
    description: "Esencia de oscuridad.",
  }),

  // =========================
  // HERRAMIENTAS
  // =========================
  lockpick: makeItem({
    id: "lockpick",
    name: "Lockpick",
    type: "tool",
    rarity: "common",
    durability: 40,
    value: 25,
    description: "Ganzúa.",
  }),
  rope: makeItem({
    id: "rope",
    name: "Rope",
    type: "tool",
    rarity: "common",
    durability: 30,
    value: 20,
    description: "Cuerda.",
  }),
  torch: makeItem({
    id: "torch",
    name: "Torch",
    type: "tool",
    rarity: "common",
    durability: 2,
    value: 5,
    description: "Antorcha.",
  }),
  pickaxe_wood: makeItem({
    id: "pickaxe_wood",
    name: "Wooden Pickaxe",
    type: "pickaxe",
    rarity: "common",
    durability: 25,
    value: 15,
    description: "Pico de madera.",
  }),
  pickaxe_stone: makeItem({
    id: "pickaxe_stone",
    name: "Stone Pickaxe",
    type: "pickaxe",
    rarity: "common",
    durability: 40,
    value: 25,
    description: "Pico de piedra.",
  }),
  pickaxe_iron: makeItem({
    id: "pickaxe_iron",
    name: "Iron Pickaxe",
    type: "pickaxe",
    rarity: "rare",
    durability: 70,
    value: 70,
    description: "Pico de hierro.",
  }),
  pickaxe_diamond: makeItem({
    id: "pickaxe_diamond",
    name: "Diamond Pickaxe",
    type: "pickaxe",
    rarity: "epic",
    durability: 90,
    value: 180,
    description: "Pico de diamante.",
  }),
  pickaxe_netherite: makeItem({
    id: "pickaxe_netherite",
    name: "Netherite Pickaxe",
    type: "pickaxe",
    rarity: "legendary",
    durability: 100,
    value: 320,
    description: "Pico de netherite.",
  }),

  // =========================
  // CONTENEDORES
  // =========================
  coin_pouch: makeItem({
    id: "coin_pouch",
    name: "Coin Pouch",
    type: "container",
    rarity: "common",
    durability: 1,
    value: 0,
    description: "Bolsa de monedas.",
  }),
  backpack_small: makeItem({
    id: "backpack_small",
    name: "Small Backpack",
    type: "container",
    rarity: "uncommon",
    durability: 1,
    value: 0,
    description: "Mochila pequeña.",
  }),
  backpack_large: makeItem({
    id: "backpack_large",
    name: "Large Backpack",
    type: "container",
    rarity: "rare",
    durability: 1,
    value: 0,
    description: "Mochila grande.",
  }),

  // =========================
  // BOMBAS
  // =========================
  bomb_smoke: makeItem({
    id: "bomb_smoke",
    name: "Smoke Bomb",
    type: "bomb",
    rarity: "rare",
    stackable: true,
    durability: 1,
    value: 50,
    description: "Bomba de humo.",
  }),
  bomb_fire: makeItem({
    id: "bomb_fire",
    name: "Fire Bomb",
    type: "bomb",
    rarity: "epic",
    stackable: true,
    durability: 1,
    value: 90,
    description: "Bomba de fuego.",
  }),

  // =========================
  // ELIXIRES
  // =========================
  elixir_life: makeItem({
    id: "elixir_life",
    name: "Life Elixir",
    type: "elixir",
    rarity: "legendary",
    stackable: true,
    durability: 1,
    value: 200,
    description: "Elixir de vida.",
  }),
  elixir_wealth: makeItem({
    id: "elixir_wealth",
    name: "Wealth Elixir",
    type: "elixir",
    rarity: "epic",
    stackable: true,
    durability: 1,
    value: 250,
    description: "Elixir de riqueza.",
  }),

  // =========================
  // ESPECIALES DE ALTO NIVEL
  // =========================
  void_armor: makeItem({
    id: "void_armor",
    name: "Void Armor",
    type: "armor",
    rarity: "mythic",
    slot: "body",
    protection: 24,
    durability: 100,
    value: 4500,
    description: "Armadura del vacío.",
  }),
  shadow_cloak: makeItem({
    id: "shadow_cloak",
    name: "Shadow Cloak",
    type: "armor",
    rarity: "legendary",
    slot: "body",
    protection: 14,
    durability: 100,
    value: 1800,
    description: "Capa sombría.",
  }),
  celestial_robe: makeItem({
    id: "celestial_robe",
    name: "Celestial Robe",
    type: "armor",
    rarity: "mythic",
    slot: "body",
    protection: 20,
    durability: 100,
    value: 3200,
    description: "Túnica celestial.",
  }),
  abyss_boots: makeItem({
    id: "abyss_boots",
    name: "Abyss Boots",
    type: "boots",
    rarity: "legendary",
    slot: "feet",
    protection: 10,
    durability: 100,
    value: 1400,
    description: "Botas del abismo.",
  }),
});

export function getItem(itemId) {
  return ITEMS[itemId] ?? null;
}

export function isItemValid(itemId) {
  return Boolean(ITEMS[itemId]);
}

export function isEquipment(itemId) {
  const item = ITEMS[itemId];
  return item ? ["weapon", "armor", "helmet", "pants", "boots", "shield", "tool", "pickaxe"].includes(item.type) : false;
}

export function createItemInstance(itemId, amount = 1) {
  const item = ITEMS[itemId];
  if (!item) return null;

  return {
    id: item.id,
    name: item.name,
    type: item.type,
    rarity: item.rarity,
    amount: item.stackable ? amount : 1,
    damage: item.damage,
    protection: item.protection,
    durability: item.maxDurability,
    maxDurability: item.maxDurability,
    slot: item.slot ?? null,
    value: item.value ?? 0,
    description: item.description ?? "",
  };
}

export function damageItem(item, amount = 1) {
  if (!item || typeof item !== "object") return item;
  const current = Number(item.durability ?? 0);
  item.durability = Math.max(0, current - amount);
  return item;
}

export function repairItem(item, amount = 1) {
  if (!item || typeof item !== "object") return item;
  const max = Number(item.maxDurability ?? 0);
  const current = Number(item.durability ?? 0);
  item.durability = Math.min(max, current + amount);
  return item;
}

export function getEquipmentBonus(itemId) {
  const item = ITEMS[itemId];
  if (!item) return { damage: 0, protection: 0 };
  return {
    damage: item.damage ?? 0,
    protection: item.protection ?? 0,
  };
}
